Repository KBIbiopharma/pybleau, pull requests merged in 2020-09, with the labels that each got.

#109 Change categorical summary
  pybleau/app/ui/dataframe_analyzer_model_view.py
  pybleau/app/ui/tests/test_dataframe_analyzer_model_view.py
Labels: maintenance

#110 Add a default mechanism for managing plot templates
  pybleau/app/model/dataframe_plot_manager.py
  pybleau/app/model/plot_template_manager.py
  pybleau/app/model/tests/test_plot_template_manager.py
  pybleau/app/plotting/i_plot_template_interactor.py
  pybleau/app/plotting/template_plot_selector.py
  pybleau/app/plotting/tests/test_template_plot_selector.py
  pybleau/app/ui/base_templates_list_dlg.py
  pybleau/app/ui/dataframe_plot_manager_view.py
  pybleau/app/ui/plot_template_manager_view.py
  pybleau/app/ui/tests/test_base_template_list_dlg.py
  pybleau/app/ui/tests/test_plot_template_manager_view.py
Labels: enhancement

#100 Add new public API for multi-df analyzer.
  pybleau/app/model/multi_dfs_dataframe_analyzer.py
  pybleau/app/model/tests/base_dataframe_analyzer.py
  pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py
Labels: enhancement

#125 Add a default for `default_plot_configs`
  pybleau/app/model/dataframe_plot_manager.py
Labels: maintenance

#134 Deserialized plots from project files and from templates do not preserve colors
  pybleau/app/io/tests/test_plot_styles_roundtrip.py
  pybleau/app/plotting/multi_plot_config.py
  pybleau/app/plotting/plot_config.py
  pybleau/app/plotting/plot_style.py
  pybleau/app/plotting/tests/test_dataframe_plot_factories.py
  pybleau/app/utils/chaco_colors.py
  pybleau/app/utils/tests/test_chaco_colors.py
Labels: bug
